[tool.ruff.lint]
select = [
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "UP", # pyupgrade
    "W",  # pycodestyle warnings
]
ignore = [
    "E501", # line too long
]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends"]

[tool.ruff.lint.isort]
known-first-party = ["apps", "contexts"]

[tool.mypy]
strict = true
files = "src"
mypy_path = ["src"]

[[tool.mypy.overrides]]
module = "pika"
ignore_missing_imports = true

[tool.pytest.ini_options]
pythonpath = "src"
